name: CI

on:
  pull_request:
  push:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: shell
      run: nix-shell --run ""

    - name: format
      run: nix-shell --run "black --check ."

    - name: tests
      run: nix-shell --run "pytest"
